.PHONY: clean All

All:
	@echo "----------Building project:[ ChallengeSolution - Debug ]----------"
	@cd "C:\Users\rmokarra\Documents\Training\Udemy_FromBeginnerToBeyond\Section16\ChallengeSolution" && "$(MAKE)" -f  "ChallengeSolution.mk"
clean:
	@echo "----------Cleaning project:[ ChallengeSolution - Debug ]----------"
	@cd "C:\Users\rmokarra\Documents\Training\Udemy_FromBeginnerToBeyond\Section16\ChallengeSolution" && "$(MAKE)" -f  "ChallengeSolution.mk" clean
